// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robinhood.proto

package com.aaron.grpc.robinhood;

public interface ApiTestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robinhood.ApiTestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double amount = 1;</code>
   * @return The amount.
   */
  double getAmount();
}
