// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robinhood.proto

package com.aaron.grpc.robinhood;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robinhood.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
