// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robinhood.proto

package com.aaron.grpc.robinhood;

public final class Robinhood {
  private Robinhood() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_QuoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_QuoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_QuoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_QuoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_BuyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_BuyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_BuyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_BuyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_SellRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_SellRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_SellResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_SellResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_ApiTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_ApiTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robinhood_ApiTestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robinhood_ApiTestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017robinhood.proto\022\trobinhood\"2\n\014LoginReq" +
      "uest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t" +
      "\"1\n\rLoginResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t\"\036\n\014QuoteRequest\022\016\n\006ticker\030\001 " +
      "\001(\t\"/\n\rQuoteResponse\022\r\n\005price\030\001 \001(\001\022\017\n\007m" +
      "essage\030\002 \001(\t\",\n\nBuyRequest\022\016\n\006ticker\030\001 \001" +
      "(\t\022\016\n\006amount\030\002 \001(\005\"/\n\013BuyResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"-\n\013SellReque" +
      "st\022\016\n\006ticker\030\001 \001(\t\022\016\n\006amount\030\002 \001(\005\"0\n\014Se" +
      "llResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002" +
      " \001(\t\" \n\016ApiTestRequest\022\016\n\006amount\030\001 \001(\001\"3" +
      "\n\017ApiTestResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t2\305\002\n\020RobinhoodService\022<\n\005LOGI" +
      "N\022\027.robinhood.LoginRequest\032\030.robinhood.L" +
      "oginResponse\"\000\022<\n\005QUOTE\022\027.robinhood.Quot" +
      "eRequest\032\030.robinhood.QuoteResponse\"\000\0226\n\003" +
      "BUY\022\025.robinhood.BuyRequest\032\026.robinhood.B" +
      "uyResponse\"\000\0229\n\004SELL\022\026.robinhood.SellReq" +
      "uest\032\027.robinhood.SellResponse\"\000\022B\n\007ApiTe" +
      "st\022\031.robinhood.ApiTestRequest\032\032.robinhoo" +
      "d.ApiTestResponse\"\000B\034\n\030com.aaron.grpc.ro" +
      "binhoodP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_robinhood_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_robinhood_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_robinhood_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_robinhood_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_LoginResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_robinhood_QuoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_robinhood_QuoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_QuoteRequest_descriptor,
        new java.lang.String[] { "Ticker", });
    internal_static_robinhood_QuoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_robinhood_QuoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_QuoteResponse_descriptor,
        new java.lang.String[] { "Price", "Message", });
    internal_static_robinhood_BuyRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_robinhood_BuyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_BuyRequest_descriptor,
        new java.lang.String[] { "Ticker", "Amount", });
    internal_static_robinhood_BuyResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_robinhood_BuyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_BuyResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_robinhood_SellRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_robinhood_SellRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_SellRequest_descriptor,
        new java.lang.String[] { "Ticker", "Amount", });
    internal_static_robinhood_SellResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_robinhood_SellResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_SellResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_robinhood_ApiTestRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_robinhood_ApiTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_ApiTestRequest_descriptor,
        new java.lang.String[] { "Amount", });
    internal_static_robinhood_ApiTestResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_robinhood_ApiTestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robinhood_ApiTestResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
