// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robinhood.proto

package com.aaron.grpc.robinhood;

public interface SellRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robinhood.SellRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticker = 1;</code>
   * @return The ticker.
   */
  java.lang.String getTicker();
  /**
   * <code>string ticker = 1;</code>
   * @return The bytes for ticker.
   */
  com.google.protobuf.ByteString
      getTickerBytes();

  /**
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();
}
