// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robinhood.proto

package com.aaron.grpc.robinhood;

public interface SellResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:robinhood.SellResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
